Update itest

diff --git a/bin/itest b/bin/itest
--- a/bin/itest
+++ b/bin/itest
@@ -27,6 +27,7 @@
 #                                                                                              
 # Source: https://unix.stackexchange.com/questions/190513/shell-scripting-proper-way-to-check-for-internet-connectivity
 
+LOCAL_IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
   GW=`netstat -nr | awk '/default/ { print $2 }' | head -1`
@@ -45,14 +46,14 @@ function portscan
   if nc -zw1 $checkdomain  80; then
     tput setaf 2; echo "Port scan good, $checkdomain port 80 available"; tput sgr0;
   else
-    echo "Port scan of $checkdomain port 80 failed."
+    tput setaf 1; echo "Port scan of $checkdomain port 80 failed."
   fi
 }
 
 function pingnet
 {
   #Google has the most reliable host name. Feel free to change it.
-  tput setaf 6; echo "Pinging $checkdomain to check for internet connection." && echo; tput sgr0;
+  tput setaf 6; echo "Pinging $checkdomain to check for internet connection..." && echo; tput sgr0;
   ping $checkdomain -c 4
 
   if [ $? -eq 0 ]
@@ -60,7 +61,7 @@ function pingnet
       tput setaf 2; echo && echo "$checkdomain pingable. Internet connection is most probably available."&& echo ; tput sgr0;
       #Insert any command you like here
     else
-      echo && echo "Could not establish internet connection. Something may be wrong here." >&2
+      tput setaf 1; echo && echo "Could not establish internet connection. Something may be wrong here." >&2
       #Insert any command you like here
 #      exit 1
   fi
@@ -69,14 +70,15 @@ function pingnet
 function pingdns
 {
   #Grab first DNS server from /etc/resolv.conf
-  tput setaf 6; echo "Pinging first DNS server in resolv.conf ($checkdns) to check name resolution" && echo; tput sgr0;
+  tput setaf 6; echo "Pinging first DNS server in resolv.conf ($checkdns) to check name resolution..." && echo; tput sgr0;
   ping $checkdns -c 4
     if [ $? -eq 0 ]
     then
-      tput setaf 6; echo && echo "$checkdns pingable. Proceeding with domain check."; tput sgr0;
+      tput setaf 2; echo && echo "$checkdns pingable."; tput sgr0;
+      tput setaf 6; echo && echo "Proceeding with domain check."; tput sgr0;
       #Insert any command you like here
     else
-      echo && echo "Could not establish internet connection to DNS. Something may be wrong here." >&2
+      tput setaf 1; echo && echo "Could not establish internet connection to DNS. Something may be wrong here." >&2
       #Insert any command you like here
 #     exit 1
   fi
@@ -84,15 +86,34 @@ function pingdns
 
 function httpreq
 {
-  tput setaf 6; echo && echo "Checking for HTTP Connectivity"; tput sgr0;
+  tput setaf 6; echo && echo "Checking for HTTP Connectivity..."; tput sgr0;
   case "$(curl -s --max-time 2 -I $checkdomain | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
   [23]) tput setaf 2; echo "HTTP connectivity is up"; tput sgr0;;
-  5) echo "The web proxy won't let us through";exit 1;;
-  *)echo "Something is wrong with HTTP connections. Go check it."; exit 1;;
+  5) tput setaf 1; echo "The web proxy won't let us through";exit 1;;
+  *) tput setaf 1; echo "Something is wrong with HTTP connections. Go check it."; exit 1;;
   esac
 #  exit 0
 }
 
+function ispinfo
+{
+  tput setaf 6; echo && echo "Checking your ISP Info..."; tput sgr0;
+  ispdata=$(curl -s --max-time 2 https://extreme-ip-lookup.com/json)
+  city=$(echo $ispdata |  jq -r '.city')
+  country=$(echo $ispdata |  jq -r '.countryCode')
+  isp=$(echo $ispdata |  jq -r '.isp')
+  host=$(echo $ispdata |  jq -r '.ipName')
+  ip=$(echo $ispdata |  jq -r '.query')
+  tput setaf 3; echo "You are online via $isp as $host from $city ($country)"; tput sgr0;
+  tput setaf 2; echo "Your public IP is: $ip"; tput sgr0;
+#  exit 0
+}
+
+
+function localip
+{
+  tput setaf 5; echo "Your local IP is: $LOCAL_IP"; tput sgr0;
+}
 
 #Ping gateway first to verify connectivity with LAN
 tput setaf 6; echo "Pinging gateway ($GW) to check for LAN connectivity" && echo; tput sgr0;
@@ -105,11 +126,14 @@ ping $GW -c 4
 
 if [ $? -eq 0 ]
 then
-  tput setaf 6; echo && echo "LAN Gateway pingable. Proceeding with internet connectivity check."; tput sgr0;
+  tput setaf 2; echo && echo "LAN Gateway pingable."; tput sgr0;
+  tput setaf 6; echo && echo "Proceeding with internet connectivity check."; tput sgr0;
   pingdns
   pingnet
   portscan
   httpreq
+  ispinfo
+  localip
   exit 0
 else
   echo && echo "Something is wrong with LAN (Gateway unreachable)"
@@ -117,6 +141,7 @@ else
   pingnet
   portscan
   httpreq
+  ispinfo
 
   #Insert any command you like here
 #  exit 1
